In [15]:
start = int(input())
end = int(input())

for i in range(start+1, end+1):
    if(i % 5 == 0):
        print(i)
        break

105


In [18]:
input_string = "chalo game ramva jaiye"
word_replace = "game"
replacement = "Garba"

A = input_string.find(word_replace)
B = A + len(word_replace)
C = input_string[:A] + replacement + input_string[B:]
print(C)

chalo Garba ramva jaiye


In [20]:
M = 6
m = "Milan"
print(M*m)

MilanMilanMilanMilanMilanMilan


In [22]:
name = input("Name : ")
print(name)

Milan


In [24]:
Int = int(input("integer : "))
print(Int)

24


In [28]:
Float = float(input("Float : "))
print(Float)

24.5


In [32]:
light = input("light :  ")

if(light == "red"):
    print("Stop")
elif(light == "green"):
    print("Go")
else:
    print("Look")

Go


In [34]:
movies = []

mov1 = input("enter 1st movie : ")
mov2 = input("enter 2nd movie : ")
mov3 = input("enter 3rd movie : ")

movies.append(mov1)
movies.append(mov2)
movies.append(mov3)

print(movies)

['Animal', 'Harry Potter', 'Jurasic World']


In [1]:
Hp = ['Animal', 'Harry Potter', 'Jurasic Park']

print(Hp[2])

Jurasic Park


In [4]:
import numpy as np
import pandas as pd

In [5]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [6]:
dates = pd.date_range("20130101", periods = 6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [7]:
dict1 = {
    "Name":['Milan', 'Raj', 'Chintu', 'Bhopo'],
    "Marks":[12, 24, 25, 23],
    "City":['Palitana', 'Bhavnagar', 'Palitana', 'Bagdana']
}

In [8]:
df = pd.DataFrame(dict1)
df

Name  Marks       City
0   Milan     12   Palitana
1     Raj     24  Bhavnagar
2  Chintu     25   Palitana
3   Bhopo     23    Bagdana

In [99]:
M = np.array([[3, 2, 1]])
M

array([[3, 2, 1]])

In [100]:
N = np.array([[44, 55, 66]])
N

array([[44, 55, 66]])

In [119]:
np.concatenate((M, N))

array([[ 3,  2,  1],
       [44, 55, 66]])

In [136]:
m = "Hello! My Name Is Milan Virash."
kayo = "Milan"
badle = "Bhopi"

haa = m.find(kayo)
naa = haa + len(kayo)
aaa = m[:haa] + badle + m[naa:]

print(aaa)

Hello! My Name Is Bhopi Virash.


In [128]:
v = M + N
v

array([[47, 57, 67]])

In [93]:
M+N

array([45, 57, 69])

In [60]:
np.max(M)

3

In [61]:
np.min(M)

1

In [62]:
np.mean(M)

2.0

In [72]:
np.average(M)

2.0

In [76]:
M.sort()
M

array([1, 2, 3])

In [83]:
M[-3]

1

In [86]:
M[::-1]

array([3, 2, 1])

In [90]:
np.sqrt(M)

array([1.        , 1.41421356, 1.73205081])

In [44]:
Sentence = "I have a Dell laptop."
company = "Dell"
replace = "HP"

this = Sentence.find(company)
then = this + len(company)
output = Sentence[:this] + replace + Sentence[then:]

print(output)

I have a HP laptop.


In [47]:
Fav_colour = ["Red", "Green", "Yellow", "White", "Black"]

for i in Fav_colour:
    print(i)

Red
Green
Yellow
White
Black


In [1]:
import numpy as np

In [13]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([6, 7, 8, 9, 10])

print(A)
print(B)
print(type(A))
print(type(B))

[1 2 3 4 5]
[ 6  7  8  9 10]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [14]:
A.shape

(5,)

In [8]:
C = A + B

print(C)

[ 7  9 11 13 15]
