In [171]:
import numpy as np

# 1D array

In [172]:
a = np.array([1, 2, 6, 8, 6])
print(a)
print(type(a))

[1 2 6 8 6]
<class 'numpy.ndarray'>


# 2D array

In [173]:
b = np.array([[1, 2, 5, 8, 6], [25, 26, 56, 58, 96]])
print(b)
print(type(b))

[[ 1  2  5  8  6]
 [25 26 56 58 96]]
<class 'numpy.ndarray'>


# 3D array

In [174]:
c = np.array([[[1, 5, 8, 6, 9], [25, 36, 85, 96, 56], [321, 654, 987, 741, 695]]])
print(c)
print(type(c))

[[[  1   5   8   6   9]
  [ 25  36  85  96  56]
  [321 654 987 741 695]]]
<class 'numpy.ndarray'>


In [175]:
# print(a.size)= we can get total number of element in that array

In [176]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


In [177]:
# print(a.shape)= we can getthe numbers of rows and columns of that array

In [178]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [179]:
# print(a.dtype)= we can get the type of data present in the array

In [180]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
int32


In [181]:
d = np.array([[1, 2, 3.5, 3, 4],
              [8, 6, 6.5, 8, 5.5],
              [6, 8, 8.5, 6.5, 5]])

print(d)
print(d.dtype)

[[1.  2.  3.5 3.  4. ]
 [8.  6.  6.5 8.  5.5]
 [6.  8.  8.5 6.5 5. ]]
float64


In [182]:
# arr.transpose()= it's replace rows with columns and columns with rows

In [183]:
d.transpose()

array([[1. , 8. , 6. ],
       [2. , 6. , 8. ],
       [3.5, 6.5, 8.5],
       [3. , 8. , 6.5],
       [4. , 5.5, 5. ]])

In [184]:
np.empty((5, 5), dtype=int)

array([[ -41853480,        386,         63,          0,          0],
       [         0,          0,          0,          0,         48],
       [1868767867,  975332708, 1886265888, 1886217518,  673741172],
       [ 891300917, 1679830057, 1701869940, 1953392957,  539763241],
       [1702389026, 1769239907, 1667198575, 1953396079,  824195618]])

In [185]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [186]:
np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [187]:
np.ones((2, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [188]:
np.zeros(4)

array([0., 0., 0., 0.])

In [189]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [190]:
np.zeros((5, 2), dtype=bool)

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [191]:
# np.arange(start, end, step)

In [192]:
np.arange(1, 20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [193]:
p = np.arange(1, 20, 2)
p

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [194]:
p = np.arange(2,20,2)
p

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [195]:
p = p.reshape((3,3))
p

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [196]:
t = np.arange(1, 100, 2)
t

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [197]:
t = t.reshape((10,5)) # convert into multidimensional array
t

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [198]:
t = t.flatten() # to convert into one dimensional array
t

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [199]:
t = t.ravel() # same as flattrn
t

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [200]:
o = np.arange(1, 51)
o = o.reshape(10, 5)
o

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [201]:
o[0]

array([1, 2, 3, 4, 5])

In [202]:
o[1]

array([ 6,  7,  8,  9, 10])

In [203]:
o[0,0]

1

In [204]:
o[3,4]

20

In [205]:
o[2:5]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [206]:
o[0:10]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [207]:
o[:, 2]

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [208]:
o[2:5, 4]

array([15, 20, 25])

In [209]:
o[:, :]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [210]:
o[:, 2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [211]:
o[:, 2:5].dtype

dtype('int32')

In [212]:
A = np.arange(0,18).reshape((6,3))
B = np.arange(20,38).reshape((6,3))
print(A)
print(B)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [213]:
A+B

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [214]:
np.add(A,B)

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [215]:
A-B

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [216]:
np.subtract(A,B)

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [217]:
A*B

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [218]:
np.multiply(A,B)

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [219]:
A/B

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [220]:
np.divide(A,B)

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [221]:
print(A.shape)
print(B.shape)

(6, 3)
(6, 3)


In [222]:
B = B.reshape((3,6))

In [223]:
print(A.shape)
print(B.shape)

(6, 3)
(3, 6)


In [224]:
A.dot(B)

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [225]:
B.max()

37

In [226]:
B.argmax() # index of that max vqlue

17

In [227]:
B.min()

20

In [228]:
np.sum(B)

513

In [229]:
np.sum(B, axis=1)

array([135, 171, 207])

In [230]:
np.sum(B, axis=0)

array([78, 81, 84, 87, 90, 93])

In [231]:
np.mean(B)

28.5

In [232]:
np.sqrt(B)

array([[4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
        5.        ],
       [5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
        5.56776436],
       [5.65685425, 5.74456265, 5.83095189, 5.91607978, 6.        ,
        6.08276253]])

In [233]:
np.std(B)

5.188127472091127

In [234]:
np.log(B)

array([[2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
        3.21887582],
       [3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
        3.4339872 ],
       [3.4657359 , 3.49650756, 3.52636052, 3.55534806, 3.58351894,
        3.61091791]])

In [235]:
l1 = np.array([20,30,40])
l2 = np.array([50,60,70])
print(l1+l2)

[ 70  90 110]
